#!/bin/sh

# set path so that rapper can be found
PATH=$PATH:/usr/local/bin

# set SDB environment vars
. /data/jena-sdb/env.sh

DATADIR=/data/Finto-data-update

TTLFILE=$DATADIR/vocabularies/metatietosanasto/metatietosanasto.ttl
RDFFILE=$DATADIR/vocabularies/metatietosanasto/metatietosanasto.rdf

# dump from MySQL to Turtle file
sdbdump --sdb=$SDBROOT/sdb-metatietosanasto.ttl \
  --graph=http://urn.fi/URN:NBN:fi:au:mts: \
  --out=TTL >$TTLFILE

minimumsize=10000
ttlsize=$(du -b "$TTLFILE" | cut -f 1)
# if successful, convert to rdfxml-abbrev using rapper
if [ $ttlsize -ge $minimumsize ]; then
    cd $DATADIR
    # fix problems with svn repo getting out of sync with github
    find . -name all-wcprops -exec rm -rf {} \;

    svn up #>/dev/null 2>/dev/null
    rapper -i turtle -o rdfxml-abbrev $TTLFILE >$RDFFILE #2>/dev/null

    rdfsize=$(du -b "$RDFFILE" | cut -f 1)
    # if successful, commit to SVN
    if [ $rdfsize -ge $minimumsize ]; then
        svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $RDFFILE -m "automaattipäivitys: metatietosanasto-kehitysversio mysql-kannasta"
        #>/dev/null 2>/dev/null
    fi
fi
