PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX mts: <http://urn.fi/URN:NBN:fi:au:mts:>

CONSTRUCT {
  mts: a owl:Ontology; owl:imports <http://www.w3.org/2004/02/skos/core> .
  ?conc a owl:Class .
  ?conc ?p ?o .
} 
FROM <http://urn.fi/URN:NBN:fi:au:mts:>
WHERE {
  <http://urn.fi/URN:NBN:fi:au:mts:m12> skos:member ?conc .
  ?conc ?p ?o .
  FILTER (?p != rdf:type)
  FILTER (?p != skos:inScheme)
  FILTER (?p != dc:source)
}
