PREFIX p: <http://www.wikidata.org/prop/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?yso skos:closeMatch ?wd .
}
WHERE {
    ?yso skos:closeMatch ?wd .
        FILTER (STRSTARTS(STR(?yso), "http://www.yso.fi/onto/yso/") &&
            STRSTARTS(STR(?wd), "http://www.wikidata.org/entity/"))
}

