PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?a skos:broader ?parent .
  ?parent skos:narrower ?a .
} WHERE {
  ?a skos:exactMatch ?b .
  ?b skos:broader ?parent .
  FILTER (!STRSTARTS(STR(?a), "http://www.yso.fi/onto/yso/"))
  FILTER (STRSTARTS(STR(?parent), "http://www.yso.fi/onto/yso/"))
}
