PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX isothes: <http://purl.org/iso25964/skos-thes#>
DELETE {
  ?group isothes:superGroup ?super .
}
INSERT {
  ?super skos:member ?group .
}
WHERE {
  ?group isothes:superGroup ?super .
}
