PREFIX afo-meta: <http://www.yso.fi/onto/afo-meta/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  ?s ?p ?o .
  FILTER (?p != dct:created)
  FILTER (?p != skos:closeMatch)
  FILTER (?p != skos:editorialNote)
  FILTER (?p != afo-meta:hasThematicGroup)
  FILTER NOT EXISTS { ?s a afo-meta:ThematicGroup }
}
