PREFIX juho-meta: <http://www.yso.fi/onto/juho-meta/>

DELETE {
  ?s juho-meta:hasLahde ?value .
}
WHERE {
  ?s juho-meta:hasLahde ?value .
};

DELETE {
  juho-meta:hasLahde ?p ?o .
}
WHERE {
  juho-meta:hasLahde ?p ?o .
}
