#!/bin/sh

SECRET=/data/onki-data/tools/svn-post-commit/secret
echo "purging Varnish cache"
varnishadm -T :6082 -S $SECRET "ban.url /"
echo "warming up cache"
/data/onki-data/tools/svn-post-commit/warmup-cache.py

