<div class="right-box">

{% if request.lang == 'sv' %}

<img src="resource/finto-pics/finto-joulu.png" alt="Gog jul!" id="finto-joulu-img" style="width: 180px;">

<h1>Tack för det gångna året!</h1>

<p>Finto-servicen önskar en god jul och ett gott nytt år!</p>

{% else %}

<img src="resource/finto-pics/finto-joulu.png" alt="Hyvää joulua!" id="finto-joulu-img" style="width: 180px;">

<h1>Kiitos kuluneesta vuodesta</h1>

<p>Finto-palvelu toivottaa hyvää joulua, leppoisaa vuodenvaihdetta ja iloista uutta vuotta!</p>

{% endif %}

</div>
