PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ysa: <http://www.yso.fi/onto/ysa/>
PREFIX yso: <http://www.yso.fi/onto/yso/>
PREFIX ysa-meta: <http://www.yso.fi/onto/ysa-meta/>
PREFIX yso-meta: <http://www.yso.fi/onto/yso-meta/2007-03-02/>
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX om: <http://www.yso.fi/onto/yso-peilaus/2007-03-02/>


CONSTRUCT {
  ?ysoc rdfs:subClassOf ?ysoparent .
}
WHERE {
  SERVICE <http://api.dev.finto.fi/sparql> {
    GRAPH <http://www.yso.fi/onto/ysa/> {
      ?ysac a skos:Concept .
      ?ysac skos:broader ?ysaparent .
    }
  }
  ?ysoc om:definedConcept ?ysac .
  FILTER EXISTS { ?ysoc a yso-meta:Concept } # much faster than a plain triple pattern...
  FILTER NOT EXISTS { ?ysoc rdfs:subClassOf ?parent }

  ?ysoparent om:definedConcept ?ysaparent .
}
