#!/bin/sh

DATADIR=/data/Finto-data-update
NEWISSUES=/data/Finto-data-update/tools/yse-updater/issues-to-triples.py
YSEDIR=/data/Finto-data-update/vocabularies/yse

cd $DATADIR
svn up
cd $YSEDIR

$NEWISSUES /etc/ysecreds 2>$YSEDIR/yse-convert.log

minimumsize=10000
actualsize=$(du -b "$YSEDIR/yse-skos.ttl" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
  svn up #>/dev/null 2>/dev/null
  find . -name all-wcprops -exec rm -rf {} \;
  svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $YSEDIR -m "automaattipäivitys: YSE" #>/dev/null 2>/dev/null
fi
