#!/bin/sh

# set SDB environment vars
. /data/jena-sdb/env.sh

MTSDIR=/data/Finto-data-update/vocabularies/metatietosanasto
TTLFILE=$MTSDIR/metatietosanasto-purify.ttl

cd $MTSDIR

# dump from MySQL to Turtle file
sdbdump --sdb=$SDBROOT/sdb-metatietosanasto.ttl \
  --graph=http://urn.fi/URN:NBN:fi:au:mts: \
  --out=TTL >$TTLFILE

minimumsize=10000
ttlsize=$(du -b "$TTLFILE" | cut -f 1)
# if successful, purify
if [ $ttlsize -ge $minimumsize ]; then
  ./purify.sh >/dev/null 2>/dev/null
fi
# if successful, load back to SDB (clear it first using sdbtruncate)
if [ $ttlsize -ge $minimumsize ]; then
  sdbtruncate --sdb=$SDBROOT/sdb-metatietosanasto.ttl --confirm
  sdbload --sdb=$SDBROOT/sdb-metatietosanasto.ttl \
    --graph=http://urn.fi/URN:NBN:fi:au:mts: $TTLFILE
fi
