#!/bin/sh

# set SDB environment vars
. /data/jena-sdb/env.sh

GDIR=/data/Finto-data-update/vocabularies/genre
TTLFILE=$GDIR/genre.ttl

cd $GDIR
svn up

# dump from MySQL to Turtle file
sdbdump --sdb=$SDBROOT/sdb-genresanasto.ttl \
  --graph=http://urn.fi/URN:NBN:fi:au:slm: \
  --out=TTL >$TTLFILE

./toskos.sh

minimumsize=10000
ttlsize=$(du -b "$TTLFILE" | cut -f 1)
# if successful, push to GitHub
if [ $ttlsize -ge $minimumsize ]; then
    svn up >/dev/null 2>/dev/null
    svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $GDIR/genre-skos.ttl $GDIR/genre.ttl $GDIR/skosify.log -m "automaattipäivitys: genresanasto" >/dev/null 2>/dev/null
fi
