#!/bin/sh

SKOSIFYHOME="/data/Skosify"
MTSDIR="/data/Finto-data-update/vocabularies/metatietosanasto"
JENABIN="/data/apache-jena/bin"

# first make sure the dumps are fresh
/etc/cron.hourly/dump-metatietosanasto-to-svn
cd $MTSDIR
svn up >/dev/null 2>/dev/null

$JENABIN/update --data=$MTSDIR/metatietosanasto.rdf --update=$MTSDIR/fix-types.rq --dump >$MTSDIR/metatietosanasto.nt

INFILES="$MTSDIR/metatietosanasto-meta.ttl $MTSDIR/metatietosanasto.nt"
OUTFILE=$MTSDIR/metatietosanasto-skos.ttl
LOGFILE=$MTSDIR/skosify.log
OPTS="-c $MTSDIR/metatietosanasto.cfg -f turtle --update-query @supergroup-to-member.rq"

$SKOSIFYHOME/skosify/skosify.py $OPTS -o $OUTFILE $INFILES 2>$LOGFILE

minimumsize=10000
actualsize=$(du -b $OUTFILE | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    svn up >/dev/null 2>/dev/null
    svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $MTSDIR/metatietosanasto-skos.ttl $MTSDIR/skosify.log -m "automaattipäivitys: metatietosanasto-julkaisuversio" >/dev/null 2>/dev/null
fi
