#!/bin/sh

# set SDB environment vars
. /data/jena-sdb/env.sh

YSODIR=/data/Finto-data-update/vocabularies/yso
TTLFILE=$YSODIR/ysoKehitys-purify.ttl

cd $YSODIR

# dump from MySQL to Turtle file
sdbdump --sdb=$SDBROOT/sdb-yso.ttl \
  --graph=http://www.yso.fi/onto/yso/ \
  --out=TTL >$TTLFILE

minimumsize=10000
ttlsize=$(du -b "$TTLFILE" | cut -f 1)
# if successful, purify
if [ $ttlsize -ge $minimumsize ]; then
  ./purify.sh >/dev/null 2>/dev/null
fi
# if successful, load back to SDB (clear it first using sdbtruncate)
ttlsize=$(du -b "$TTLFILE" | cut -f 1)
if [ $ttlsize -ge $minimumsize ]; then
  sdbtruncate --sdb=$SDBROOT/sdb-yso.ttl --confirm
  sdbload --sdb=$SDBROOT/sdb-yso.ttl \
    --graph=http://www.yso.fi/onto/yso/ $TTLFILE
fi
