#!/bin/sh

export PATH=$PATH:/usr/local/bin

DATADIR=/data/Finto-data-update
YSOPDIR=vocabularies/yso-paikat

cd $DATADIR
svn up >/dev/null 2>/dev/null

cd $DATADIR/$YSOPDIR
./toskos.sh

cd $DATADIR
find . -name all-wcprops -exec rm -rf {} \;
svn up 
svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $DATADIR/$YSOPDIR -m "automaattipäivitys: YSO-paikat" >/dev/null 2>/dev/null
