#!/bin/sh

DATADIR=/data/Finto-data-update
CNDIR=vocabularies/cn

cd $DATADIR
svn up >/dev/null 2>/dev/null

cd $DATADIR/$CNDIR
./update-cn.sh
./toskos.sh

minimumsize=10000
actualsize=$(du -b "$DATADIR/$CNDIR/cn-skos.ttl" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cd $DATADIR
    find . -name all-wcprops -exec rm -rf {} \;
    svn up
    svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $DATADIR/$CNDIR -m "automaattipäivitys: yhteisönimet" >/dev/null 2>/dev/null
else
    cat $DATADIR/$CNDIR/cn.log | mail -s "CN update failed" kk-finto@helsinki.fi
fi
