#!/bin/sh


DATADIR=/data/Finto-data-update
OAITOSKOS=tools/oai-pmh-to-skos/oai-pmh-to-skos.py
LINK=tools/oai-pmh-to-skos/link-ysa-allars.py
YSADIR=vocabularies/ysa
YSODIR=vocabularies/yso
YSOPDIR=vocabularies/yso-paikat
ALLARSDIR=vocabularies/allars

cd $DATADIR
svn up

$OAITOSKOS https://fennica.linneanet.fi/cgi-bin/oai-pmh-fennica-ysa.cgi subjects http://www.yso.fi/onto/ysa/Y ysa allars >$YSADIR/ysa.ttl 2>$YSADIR/ysa-convert.log
$OAITOSKOS https://alma.linneanet.fi/cgi-bin/oai-pmh-alma-asteri-allars.cgi subjects http://www.yso.fi/onto/allars/Y allars ysa >$ALLARSDIR/allars.ttl 2>$ALLARSDIR/allars-convert.log
$LINK $YSADIR/ysa.ttl $ALLARSDIR/allars.ttl $YSODIR/yso-skos.ttl $YSOPDIR/yso-paikat-skos.ttl $YSADIR/ysa-linked.ttl $ALLARSDIR/allars-linked.ttl 2>$YSADIR/link-ysa-allars-yso.log

cd $DATADIR/$YSADIR
./toskos.sh

cd $DATADIR/$ALLARSDIR
./toskos.sh

cd $DATADIR
find . -name all-wcprops -exec rm -rf {} \;
svn up #>/dev/null 2>/dev/null
svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $DATADIR/$YSADIR $DATADIR/$ALLARSDIR -m "automaattipäivitys: YSA, Allars" #>/dev/null 2>/dev/null
