#!/bin/sh

SKOSIFYHOME="/data/Skosify"
YSODIR="/data/Finto-data-update/vocabularies/yso"
TIMESTAMPER="$YSODIR/../../tools/timestamper/timestamper.py"
EXPANDURIS="$YSODIR/../../tools/expand-note-uris/expand-note-uris.py"
JENABIN="/data/apache-jena/bin"
RAPPER="/usr/local/bin/rapper"

# first make sure the dumps are fresh
/etc/cron.hourly/dump-yso-to-svn
cd $YSODIR
svn up >/dev/null 2>/dev/null

# add koko exactMatches
$JENABIN/sparql --data=$YSODIR/../koko/koko.ttl --query=$YSODIR/add-koko-matches.rq > $YSODIR/koko-matches.ttl

# convert ysa and allars matches
$YSODIR/convert-match-properties.py $YSODIR/ysoKehitys.ttl $YSODIR/ysoKehitys-matched.ttl

# expand URIs in notes and definitions
$EXPANDURIS $YSODIR/ysoKehitys-matched.ttl >$YSODIR/ysoKehitys-expanded.ttl

$SKOSIFYHOME/skosify/skosify.py \
	-c $YSODIR/../../conf/skosify/finnonto.cfg \
	$YSODIR/yso-metadata.ttl \
	$YSODIR/ysoKehitys-expanded.ttl \
	$YSODIR/koko-matches.ttl \
	-F turtle \
	2>$YSODIR/skosify.log | $TIMESTAMPER $YSODIR/timestamps.tsv >$YSODIR/yso-skos.ttl

# count the top concepts and complain loudly if it's not 3
count=`$RAPPER -q -i turtle $YSODIR/yso-skos.ttl | grep -c 'topConceptOf> <http://www.yso.fi/onto/yso/>'`
if [ "$count" -ne 3 ]; then
    topconcepts=`$RAPPER -q -i turtle $YSODIR/yso-skos.ttl | grep 'topConceptOf> <http://www.yso.fi/onto/yso/>'`
    echo -e "YSOssa $count yläkäsitettä (pitäisi olla 3), ei voida julkaista!\n\n$topconcepts" | mail -s "Ongelma YSOn yläkäsitteissä" kk-finto@helsinki.fi
    exit 1
fi

minimumsize=10000
actualsize=$(du -b "$YSODIR/yso-skos.ttl" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    svn up >/dev/null 2>/dev/null
    svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $YSODIR/yso-skos.ttl $YSODIR/skosify.log $YSODIR/timestamps.tsv -m "automaattipäivitys: yso-julkaisuversio" >/dev/null 2>/dev/null
fi
