#!/bin/sh

DATADIR=/data/Finto-data-update

dir=$DATADIR/vocabularies/kassu
file=kassu-skos.ttl.new

cd $dir

wget -O "$file" 'http://onki.fi/fi/browser/downloadfile/kassu?o=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fkassu&f=kassu%2Fkassu-skos.ttl' >$dir/wget.out 2>$dir/wget.err

minimumsize=10000
actualsize=$(du -b "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    svn up
    mv "$file" kassu-skos.ttl
    svn ci --username Finto-data --password PASSWORD kassu-skos.ttl -m "automaattipäivitys: kassu" #>/dev/null 2>/dev/null
fi
