#!/bin/sh

DATADIR=/data/Finto-data-update
OAITOSKOS=tools/oai-pmh-to-skos/oai-pmh-to-skos.py
SEKODIR=vocabularies/seko

cd $DATADIR
svn up

$OAITOSKOS https://viola.linneanet.fi/cgi-bin/oai-pmh-viola-finto.cgi subjects 'http://urn.fi/urn:nbn:fi:au:seko:' seko >$SEKODIR/seko.ttl 2>$SEKODIR/seko-convert.log

cd $DATADIR/$SEKODIR
./toskos.sh

cd $DATADIR
find . -name all-wcprops -exec rm -rf {} \;
svn up #>/dev/null 2>/dev/null
svn ci --username Finto-data --password PASSWORD --no-auth-cache --non-interactive $DATADIR/$SEKODIR -m "automaattipäivitys: SEKO" #>/dev/null 2>/dev/null
