{% if request.lang == 'fi' %}
<h4>Tietoja</h4>
<p>Finto.fi on avoin palvelu yhteentoimivuutta edistävien sanastojen, ontologioiden ja luokitusten julkaisua ja käyttöä varten. Finto.fi:stä löydät käyttöliittymän sanastojen selailulle, sekä <a href="http://api.finto.fi/">avoimet rajapinnat</a> sanastojen hyödyntämiseen muissa sovelluksissa.</p>

<p>Finto.fi:tä kehitetään osana Kansalliskirjaston Finto-palvelua. Lisätietoa sekä yhteystiedot löydät <a href="https://www.kiwi.fi/display/Finto">Finto-palvelun asiakaswikistä</a>. Jos kohtaat ongelmia tai sinulla on kehitysideoita palvelun suhteen, otathan yhteyttä Finton kehittäjiin.</p>

<p>Finto-palvelua hyödynnetään laajasti Suomessa kulttuuriperintöorganisaatioista julkishallinnon organisaatioihin. Finton työkalujen kansainväliseen käyttäjäkuntaan lukeutuvat mm. UNESCO ja YK:n elintarvike- ja maatalousjärjestö FAO. Finton käyttäjätarinoita voit lukea <a href="https://www.kiwi.fi/x/hgKEBw">täältä</a>. Jaa myös oma tarinasi meille ja muille!</p>

<p>Voit ehdottaa uusia käsitteitä ja muutoksia Yleiseen suomalaiseen ontologiaan ja YSO-paikkoihin <a href="http://ehdotus.finto.fi">Ehdotusjärjestelmän</a> avulla. Käsittelyssä olevia käsite-ehdotuksia voit selata <a href="https://finto.fi/yse/fi">Finton YSE-sanastossa</a>. Muita sanastoja koskevaa palautetta voit lähettää <a href="http://finto.fi/fi/feedback">Palaute-sivun</a> kautta.</p>

<p><a href="https://www.kiwi.fi/pages/viewpage.action?pageId=187729020" target="_blank">Saavutettavuusseloste</a></p>

{% elseif request.lang == 'sv' %}
<h4>Information</h4>
<p>Finto.fi är en öppen service för publicering och användning av samverkansfrämjande tesaurer, ontologier och klassifikationer. Finto.fi erbjuder ett användargränssnitt för bläddring i vokabulärerna, samt <a href="http://api.finto.fi/">öppna gränssnitt</a> för användning av vokabulärerna i andra applikationer.</p>

<p>Finto.fi utvecklas som en del av Nationalbibliotekets Finto-service. Mer information samt kontaktuppgifter finns i <a href="https://www.kiwi.fi/display/Finto">Finto-servicens kundwiki</a>. Kontakta utvecklarna av Finto om du stöter på problem eller om du har utvecklingsidéer för servicen.</p>

<p>Finto-servicen är i utbredd användning inom finländska organisationer för kulturarv och för offentlig förvaltning. Till den internationella användarkretsen av Fintos verktyg hör bl.a. UNESCO och FN:s livsmedels- och jordbruksorganisation FAO. Du kan läsa Fintos användarberättelser <a href="https://www.kiwi.fi/x/hgKEBw">här</a>. Dela också din egen berättelse med oss och med andra!</p>

<p>Du kan föreslå nya begrepp och ändringar till Allmän finländsk ontologi och ALLFO-orter via <a href="http://ehdotus.finto.fi">Förslagssystemet</a>. Begreppsförslag som är under behandling kan du söka i <a href="http://finto.fi/yse">YSE-vokabulären</a> i Finto. Förslag gällande andra vokabulärer och ontologier i Finto kan du skicka via <a href="http://finto.fi/sv/feedback">Respons-sidan</a>.</p>

<p><a href="https://www.kiwi.fi/pages/viewpage.action?pageId=187729020" target="_blank">Tillgänglighetsutlåtande</a></p>

{% elseif request.lang == 'en' %}
<h4>Information</h4>
<p>Finto.fi is an open service for the publication and use of vocabularies, ontologies and classifications with an objective to promote interoperability. Finto.fi offers a browsing interface for vocabularies as well as <a href="http://api.finto.fi/">open APIs</a> for their integration into other applications.</p>

<p>Finto.fi is developed in the National Library of Finland as part of Finto service. For more information and contact info, please visit <a href="https://www.kiwi.fi/display/Finto">Finto customer wiki</a>. In case of problems or development ideas, please contact Finto developers.</p>

<p>Finto service has a wide range of users in Finland from culture heritage organizations to public administration. International users include UNESCO and FAO. Read more about Finto's users <a href="https://www.kiwi.fi/x/hgKEBw">here</a>. To share your own user story, please contact us.</p>

<p>Suggestions to General Finnish Ontology YSO and YSO places for new additions or changes can be made from this page. To find all such suggestions still in process, please see the <a href="http://finto.fi/yse">suggestion vocabulary YSE</a>. Suggestions or feedback to other vocabularies and ontologies can be sent via the <a href="http://finto.fi/en/feedback">feedback</a> form.</p>

{% endif %}
