{% if request.lang == 'fi' %}
<h4>Tietoja</h4>
<p>Finto on suomalainen palvelu sanastojen, ontologioiden ja luokitusten julkaisua ja käyttöä varten. Finto tarjoaa käyttöliittymän sanastojen selailulle, sekä <a href="http://api.finto.fi/">avoimet rajapinnat</a>sanastojen hyödyntämiseen muissa sovelluksissa.</p>
<p>Fintoa kehitetään Kansalliskirjaston, opetus- ja kulttuuriministeriön ja valtiovarainministeriön yhteisessä projektissa. Lisätietoa löydät<a href="https://www.kiwi.fi/display/Finto/">Finto-palvelun asiakaswikistä</a>sekä<a href="https://www.kiwi.fi/display/Asiasanastotjaontologiat/">Asiasanastot ja ontologiat -asiakaswikistä.</a></p>

<p>Kansalliskirjasto jatkaa Aalto-yliopistossa ja Helsingin yliopistossa vuosina 2003 - 2012 toimineen<a href="http://www.seco.tkk.fi/projects/finnonto/index.fi.php/">FinnONTO-hankkeen työtä.</a></p>

<p>Jos kohtaat ongelmia tai sinulla on kehitysideoita palvelun suhteen, ota yhteyttä Finton kehittäjiin. Olemme myös erittäin kiinnostuneita sinun menestystarinoistasi Finton käytössä - <a href="../fi/feedback">jaa kokemuksiasi meille ja muille!</a></p>      
<p>Voit ehdottaa uusia käsitteitä ja muutoksia YSAan ja YSOon oheisen<a href="//ehdotus.finto.fi/">lomakkeen avulla.</a>Käsittelyssä olevia käsite-ehdotuksia voit selata<a href="../yse/fi">myös Fintossa.</a></p>      

{% elseif request.lang == 'sv' %}
<h4>Information</h4>
<p>Finto är en finländsk service för publicering och användning av tesaurusar, ontologier och klassifikationer. Finto erbjuder ett användargränssnitt för direkt användning av vokabulärerna och<a href="http://api.finto.fi/">öppna grässnitt</a>för användning i andra applikationer.</p>
<p>Finto utvecklas inom ett gemensamt projekt för Nationalbiblioteket, undervisnings- och kulturministeriet samt finansministeriet. Mer 
information finns i <a href="https://www.kiwi.fi/pages/viewpage.action?pageId=44237306">Finto-servicens kundwiki</a> och i <a href="https://www.kiwi.fi/pages/viewpage.action?pageId=43451759">kundwikin för tesaurer och ontologier</a>.</p>

<p>Projektet fortsätter det arbete som gjorts i FinnONTO-projektet vid Aalto-universitetet och Helsingfors universitet under åren 2003-2012:<a href="http://www.seco.tkk.fi/projects/finnonto/index.fi.php/">FinnONTO</a></p>

<p>Ta kontakt med utvecklarna av Finto om du stöter på problem eller om du har utvecklingsidéer gällande servicen. Vi är också mycket intresserade av dina framgångar med användningen av Finto -<a href="../sv/feedback"> dela dina erfarenheter med oss och med andra!</a></p>      
<p>Du kan föreslå nya begrepp och ändringar till Allärs och ALLFO med<a href="//ehdotus.finto.fi/">denna blankett.</a>Begreppsförslag som är under behandling kan du också söka<a href="../yse/sv">i Finto.</a></p>      

{% elseif request.lang == 'en' %}
<h4>About</h4>
<p>Finto is a Finnish service for the publication and utilization of vocabularies, ontologies and classifications. It provides a user interface for browsing the vocabularies and<a href="http://api.finto.fi/">open interfaces</a>for utilizing them in other applications.</p>
<p>The service is being developed as a joint venture between the National Library of Finland, the Ministry of Finance, and the Ministry of Education and Culture. For more information, please visit <a href="https://www.kiwi.fi/display/Finto/In+English">the customer wiki of the Finto service</a> and <a href="https://www.kiwi.fi/display/Asiasanastotjaontologiat/In+English">the customer wiki of thesauri and ontologies</a>.</p>

<p>The project is a continuation of the work begun in a joint research project FinnONTO between the Aalto University and the University of Helsinki from 2003 to 2012.<a href="http://www.seco.tkk.fi/projects/finnonto/index.fi.php/">See FinnONTO Homepage</a></p>

<p>If you encounter any problems or have improvement ideas, please contact the Finto team. We are also very much interested in your success stories in using Finto -<a href="../en/feedback"> please share your experiences!</a></p>      

{% endif %}

