{% if request.lang == 'fi' %}
<h4>Tietoja</h4>
<p>Finto on suomalainen palvelu sanastojen, ontologioiden ja luokitusten julkaisua ja käyttöä varten. Finto tarjoaa käyttöliittymän sanastojen selailulle, sekä <a href="http://api.finto.fi/">avoimet rajapinnat</a>sanastojen hyödyntämiseen muissa sovelluksissa.</p>
<p>Fintoa kehitetään Kansalliskirjaston, opetus- ja kulttuuriministeriön ja valtiovarainministeriön yhteisessä<a href="https://www.kiwi.fi/display/Finto/">Finto-projektissa.</a></p>

<p>ONKI-projekti jatkaa Aalto-yliopistossa ja Helsingin yliopistossa vuosina 2003 - 2012 toimineen<a href="http://www.seco.tkk.fi/projects/finnonto/index.fi.php/">FinnONTO-hankkeen työtä.</a></p>

<p>Jos kohtaat ongelmia tai sinulla on kehitysideoita palvelun suhteen, ota yhteyttä Finton kehittäjiin. Olemme myös erittäin kiinnostuneita sinun menestystarinoistasi Finton käytössä - <a href="../fi/feedback">jaa kokemuksiasi meille ja muille!</a></p>      

{% elseif request.lang == 'sv' %}
<h4>Information</h4>
<p>Finto är en finländsk service för publicering och användning av tesaurusar, ontologier och klassifikationer. Finto erbjuder ett användargränssnitt för direkt användning av vokabulärerna och<a href="http://api.finto.fi/">öppna grässnitt</a>för användning i andra applikationer.</p>
<p>Finto utvecklas i ONKI-projektet, som är ett gemensamt projekt mellan Nationalbiblioteket, Undervisnings- och kulturministeriet och Finansministeriet:<a href="https://www.kiwi.fi/pages/viewpage.action?pageId=44237306">Fintos wikisida</a></p>

<p>ONKI-projektet fortsätter det arbete som gjorts i FinnONTO-projektet vid Aalto-universitetet och Helsingfors universitet under åren 2003-2012:<a href="http://www.seco.tkk.fi/projects/finnonto/index.fi.php/">FinnONTO</a></p>

<p>Ta kontakt med utvecklarna av Finto om du stöter på problem eller om du har utvecklingsidéer gällande servicen. Vi är också mycket intresserade av dina framgångar med användningen av Finto -<a href="../sv/feedback"> dela dina erfarenheter med oss och med andra!</a></p>      

{% elseif request.lang == 'en' %}
<h4>About</h4>
<p>Finto is a Finnish service for the publication and utilization of vocabularies, ontologies and classifications. It provides a user interface for browsing the vocabularies and<a href="http://api.finto.fi/">open interfaces</a>for utilizing them in other applications.</p>
<p>Finto is being developed by the ONKI Project as a joint venture between the National Library of Finland, the Ministry of Finance, and the Ministry of Education and Culture.<a href="https://www.kiwi.fi/display/Finto/In+English">See Project Wiki</a></p>

<p>The project is a continuation of the work begun in a joint research project FinnONTO between the Aalto University and the University of Helsinki from 2003 to 2012.<a href="http://www.seco.tkk.fi/projects/finnonto/index.fi.php/">See FinnONTO Homepage</a></p>

<p>If you encounter any problems or have improvement ideas, please contact the Finto team. We are also very much interested in your success stories in using Finto -<a href="../en/feedback"> please share your experiences!</a></p>      

{% endif %}

