<div class="right-box">
{% if request.lang == 'fi' %}

<h1>Finto 10 vuotta!</h1>
<img src="resource/finto-pics/finto10.png" alt="" id="finto10-img">

<p>Finto-palvelu täyttää tänä vuonna 10 vuotta! Juhlaseminaari järjestetään pe 1.11. Hotel Arthurin juhlasalissa, Helsingissä. Tervetuloa seminaariin paikalle tai
etänä!</p>

<p><a href="https://www.lyyti.fi/reg/Finto10v">Ilmoittaudu</a></p>

{% elseif request.lang == 'sv' %}

<h1>Finto 10 år!</h1>
<img src="resource/finto-pics/finto10.png" alt="" id="finto10-img">

<p>Finto-servicen firar 10-årsjubileum i år! Ett festseminarium ordnas fredagen den 1.11 i Hotel Arthurs festsal i Helsingfors. Välkomna till seminariet på plats eller på
distans!</p>

<p><a href="https://www.lyyti.fi/reg/Finto10v">Anmälning</a></p>

{% elseif request.lang == 'en' %}

<h1>Finto 10 years!</h1>
<img src="resource/finto-pics/finto10.png" alt="" id="finto10-img">

<p>Finto service turns 10 this year! The Anniversary Seminar is held on Friday, 1 November at Hotel Arthur's Ballroom, Helsinki. Streaming is available. The programme will be in Finnish.
Welcome!</p>

<p><a href="https://www.lyyti.fi/reg/Finto10v">Register</a></p>

{% elseif request.lang == 'se' %}

<h1>Finto 10 jagi!</h1>
<img src="resource/finto-pics/finto10.png" alt="" id="finto10-img">

<p>Finto-bálvalus deavdá dán jagi 10 jagi! Ávvuseminára lágiduvvo be 1.11. Hotel Arthur riepmosáles, Helssegis. Buresboahtin seminárii báikki ala dahje
gáiddusin!</p>

<p><a href="https://www.lyyti.fi/reg/Finto10v">Almmut</a></p>

{% endif %}
</div>
