<div class="right-box">
{% if lang == 'fi' %}
<h1>Finto Twitterissä</h1>
{% elseif lang == 'sv' %}
<h1>Finto på Twitter</h1>
{% elseif lang == 'en' %}
<h1>Finto on Twitter</h1>
{% elseif lang == 'se' %}
<h1>Finto Twitteris</h1>
{% endif %}
<a class="twitter-timeline" height="330" data-dnt="true" data-link-color="#00748f" data-chrome="nofooter noborders" href="https://twitter.com/Fintopalvelu" data-widget-id="466581978829950976">Tweets by @Fintopalvelu</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
