PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (STR(?wikidata_uri) AS ?full_uri) (SUBSTR(STR(?date), 1, 10) AS ?date_yyyy_mm_dd)
WHERE {
    ?wikidata_uri wikibase:rank ?rank ;
                  prov:wasDerivedFrom ?ref .
    ?ref pr:P813 ?date .
}
